behaviors:
  CarAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 0.0001
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
    keep_checkpoints: 5
    max_steps: 60000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
environment_parameters:
  episodes_before_rebuild:
    curriculum:
      - name: Initial
        value: 200
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.4
      - name: Intermediate
        value: 100
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.6
      - name: Advanced
        value: 50
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.8
      - name: Expert
        value: 25
  max_time_without_checkpoint:
    curriculum:
      - name: Beginner
        value: 8
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.5
      - name: Intermediate
        value: 6
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.6
      - name: Advanced
        value: 3
  no_progress_threshold_time:
    curriculum:
      - name: Initial
        value: 12
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.4
      - name: Advanced
        value: 5
  maxWaitTimeForSynchronization:
    curriculum:
      - name: Default
        value: 20
  speed_reward:
    curriculum:
      - name: Basic
        value: 0.05
  checkpoint_reward:
    curriculum:
      - name: Basic
        value: 1
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.5
      - name: Advanced
        value: 2
  direction_alignment_reward:
    curriculum:
      - name: Initial
        value: 0.2
  lapCompletionReward:
    curriculum:
      - name: Initial
        value: 8
  survival_bias:
    curriculum:
      - name: Initial
        value: 0.002
  backwards_penalty:
    curriculum:
      - name: Basic
        value: -2
  no_progress_penalty:
    curriculum:
      - name: Basic
        value: -0.2
  reverse_penalty:
    curriculum:
      - name: Basic
        value: -0.15
  collision_penalty:
    curriculum:
      - name: Initial
        value: -10
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.8
      - name: Advanced
        value: -20
  use_strict_resets:
    curriculum:
      - name: InitialStrict
        value: 1
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.4
      - name: GradualTransition
        value: 0.75
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.5
      - name: FurtherTransition
        value: 0.5
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.7
      - name: MinimalResets
        value: 0.25
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.8
      - name: RecoveryMode
        value: 0
  longDriftReward:
    curriculum:
      - name: Initial
        value: 10.0
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.4
      - name: Advanced
        value: 15.0
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.5
      - name: Elite
        value: 20.0
  failedDriftPenalty:
    curriculum:
      - name: Initial
        value: -2.0 
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.4
      - name: Intermediate
        value: -3.0
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.5
      - name: Advanced
        value: -5.0
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 0
          threshold: 0.7
      - name: Elite
        value: -8.0

