behaviors:
  CarAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256  
      num_layers: 3      
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000000
    time_horizon: 64
    summary_freq: 10000
    threaded: true

# Environment parameters with enhanced curriculum features
environment_parameters:
  # Track generation frequency
  track_rebuild_episodes:
    curriculum:
      - name: Initial
        value: 1000

  # Timeout parameters
  max_time_without_checkpoint:
    curriculum:
      - name: Beginner
        value: 20.0
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 100000
          threshold: 0.5
      - name: Intermediate
        value: 30.0

  # New parameter - time to wait for progress before penalty
  no_progress_threshold_time:
    curriculum:
      - name: Initial
        value: 3.0
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 100000
          threshold: 0.4
      - name: Intermediate 
        value: 5.0
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 150000
          threshold: 0.5
      - name: Advanced
        value: 8.0

  # Agent synchronization timeout
  maxWaitTimeForSynchronization:
    curriculum:
      - name: Initial
        value: 10.0
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 50000
          threshold: 0.3
      - name: Advanced
        value: 20.0

  # Reward parameters
  speed_reward:
    curriculum:
      - name: Basic
        value: 0.08
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 200000
          threshold: 0.6
      - name: Advanced
        value: 0.1
          
  checkpoint_reward:
    curriculum:
      - name: Basic
        value: 5.0
        
  # Direction alignment reward
  direction_alignment_reward:
    curriculum:
      - name: Initial
        value: 0.05
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 100000
          threshold: 0.4
      - name: Cornering
        value: 0.2
        
  # Cornering reward for arcade racing techniques
  cornering_reward:
    curriculum:
      - name: Initial
        value: 0.15
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 100000
          threshold: 0.4
      - name: Advanced
        value: 0.3
        
  # Recovery reward
  recovery_reward:
    curriculum:
      - name: Initial
        value: 0.5
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 150000
          threshold: 0.5
      - name: Advanced
        value: 1.0
        
  # Penalty parameters
  backwards_penalty:
    curriculum:
      - name: Basic
        value: -0.08
        
  no_progress_penalty:
    curriculum:
      - name: Basic
        value: -0.005
        
  reverse_penalty:
    curriculum:
      - name: Basic
        value: -0.2
  
  # Collision penalty
  collision_penalty:
    curriculum:
      - name: InitialLearning
        value: -0.1
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 200000
          threshold: 0.6
      - name: AdvancedLearning
        value: -0.2
        
  # Reset settings
  use_strict_resets:
    curriculum:
      - name: InitialStrict
        value: 1.0
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 100000
          threshold: 0.3
      - name: TransitionToRecovery
        value: 0.0
        
  episodes_to_switch_collision:
    curriculum:
      - name: Default
        value: 5000
        
  randomize_starts:
    curriculum:
      - name: Initial
        value: 1.0
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 50000
          threshold: 0.3
      - name: Randomized
        value: 1.0
        
  # Perturbation parameters
  perturbation_chance:
    curriculum:
      - name: Initial
        value: 0.01
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 50000
          threshold: 0.4
      - name: Intermediate
        value: 0.05
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 100000
          threshold: 0.6
      - name: Advanced
        value: 0.1
        
  perturbation_strength:
    curriculum:
      - name: Initial
        value: 200.0
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 50000
          threshold: 0.4
      - name: Intermediate
        value: 500.0
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 100000
          threshold: 0.6
      - name: Advanced
        value: 1000.0
        
  start_randomization:
    curriculum:
      - name: Initial
        value: 0.5
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 50000
          threshold: 0.4
      - name: Intermediate
        value: 1.0
        completion_criteria:
          measure: progress
          behavior: CarAgent
          min_lesson_length: 100000
          threshold: 0.5
      - name: Advanced
        value: 2.0